### ISSUE TITLE
error: run python yolo_pose_onnx_inference.py

### ISSUE THREAD

**Issue by dongxiaolong** [TexasInstruments/edgeai-yolov5#20]
Traceback (most recent call last):
  File "yolo_pose_onnx_inference.py", line 123, in <module>
    main()
  File "yolo_pose_onnx_inference.py", line 118, in main
    model_inference_image_list(model_path=args.model_path, img_path=args.img_path,
  File "yolo_pose_onnx_inference.py", line 70, in model_inference_image_list
    post_process(img_file, dst_file, output[0], score_threshold=0.3)
  File "yolo_pose_onnx_inference.py", line 89, in post_process
    img = cv2.rectangle(img, (int(det_bbox[0]), int(det_bbox[1])), ((det_bbox[2]), (det_bbox[3])), color_map[::-1], 2)
cv2.error: OpenCV(4.5.5) :-1: error: (-5:Bad argument) in function 'rectangle'
> Overload resolution failed:
>  - Can't parse 'pt2'. Sequence item with index 0 has a wrong type
>  - Can't parse 'pt2'. Sequence item with index 0 has a wrong type
>  - Can't parse 'rec'. Expected sequence length 4, got 2
>  - Can't parse 'rec'. Expected sequence length 4, got 2

**Comment by dongxiaolong** [comment]
fix this bug by:
`vim yolo_pose_onnx_inference.py`
change line 89:
`img = cv2.rectangle(img, (det_bbox[0], det_bbox[1]), (det_bbox[2], det_bbox[3]), color_map[::-1], 2)`
to:
`img = cv2.rectangle(img, (int(det_bbox[0]), int(det_bbox[1])), (int(det_bbox[2]), int(det_bbox[3])), color_map[::-1], 2)`
this bug maybe as the box coordinate type is float, change to int may fix the bug.
