### ISSUE TITLE
Run Error with torch 1.11.0+cu113 CUDA:0 python3.9

### ISSUE THREAD

**Issue by BoshiLee** [TexasInstruments/edgeai-yolov5#91]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
 - **Common dataset**: coco.yaml or coco128.yaml
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#environments
 
If this is a custom dataset/training question you **must include** your `train*.jpg`, `val*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## 🐛 Bug
python .\detect.py --weights Yolov5s6_pose_640.pt --source 0 --kpt-label
Encounter error when run detect.py

## To Reproduce (REQUIRED)

Just clone pose branch and run command
python .\detect.py --weights Yolov5s6_pose_640.pt --source 0 --kpt-label

Output:
```
Namespace(weights=['Yolov5s6_pose_640.pt'], source='0', img_size=640, conf_thres=0.55, iou_thres=0.45, device='0', view_img=False, save_txt=False, save_txt_tidl=False, save_bin=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, update=False, project='runs/detect', name='exp', exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, kpt_label=True)
YOLOv5  2022-12-6 torch 1.11.0+cu113 CUDA:0 (NVIDIA GeForce RTX 2070 with Max-Q Design, 8191.6875MB)

Fusing layers...
Model Summary: 299 layers, 12545740 parameters, 0 gradients
1/1: 0...  success (640x480 at 30.00 FPS).

Traceback (most recent call last):
  File "D:\share\edgeai-yolov5\detect.py", line 204, in <module>
    detect(opt=opt)
  File "D:\share\edgeai-yolov5\detect.py", line 65, in detect
    model(torch.zeros(1, 3, imgsz, imgsz).to(device).type_as(next(model.parameters())))  # run once
  File "C:\Users\snick\miniconda3\envs\yolo_pose_py39\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\share\edgeai-yolov5\models\yolo.py", line 157, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "D:\share\edgeai-yolov5\models\yolo.py", line 188, in forward_once
    x = m(x)  # run
  File "C:\Users\snick\miniconda3\envs\yolo_pose_py39\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\snick\miniconda3\envs\yolo_pose_py39\lib\site-packages\torch\nn\modules\upsampling.py", line 154, in forward
    recompute_scale_factor=self.recompute_scale_factor)
  File "C:\Users\snick\miniconda3\envs\yolo_pose_py39\lib\site-packages\torch\nn\modules\module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'
```

## Expected behavior
Start detection like torch==1.8.1

## Environment
(yolo_pose_py39) PS D:\share\edgeai-yolov5> python
Python 3.9.15 (main, Nov 24 2022, 14:39:17) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.11.0+cu113'

**Comment by divided-by-7** [comment]
Maybe you can try to downgrade your pytorch version == 1.9
